SELECT
    t.PICKUP_HOUR,
    t.RIDES AS actual_rides,
    p.PREDICTED_RIDES AS predicted_rides
FROM
    NYC_DATA.PUBLIC.YELLOW_TAXI_DATA_TRANSFORMED t
LEFT JOIN
    NYC_DATA.PUBLIC.YELLOW_TAXI_DATA_PREDICTIONS p
    ON t.PICKUP_HOUR = p.PICKUP_HOUR
    AND t.PICKUP_LOCATION_ID = p.PICKUP_LOCATION_ID
WHERE
    t.PICKUP_LOCATION_ID = 43
    AND t.PICKUP_HOUR >= DATEADD(year, -1, CURRENT_DATE - INTERVAL '30 day')
    AND t.PICKUP_HOUR < DATEADD(year, -1, CURRENT_DATE + INTERVAL '10 day')
ORDER BY
    t.PICKUP_HOUR